[tool.poetry]
name = "rag-cloudsql"
version = "0.1.0"
description = "RAG using CloudSQL for Postgres"
authors = ["Google LLC <googleapis-packages@google.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, ^3.11"
langchain = ">=0.2.5"
langchain-core = ">=0.2.36, <1.0.0"
langchain-google-cloud-sql-pg = ">=0.10.0"
langchain-google-vertexai = ">=2.0.0"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_cloudsql"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Google LLC"
integrations = ["VertexAI", "CloudSQL"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
