name: API docs build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'
env:
  POETRY_VERSION: "1.8.1"
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          path: langchain
      - uses: actions/checkout@v4
        with:
          repository: langchain-ai/langchain-api-docs-html
          path: langchain-api-docs-html
          token: ${{ secrets.TOKEN_GITHUB_API_DOCS_HTML }}
      - name: Test add file
        working-directory: langchain-api-docs-html
        run: |
          echo "Hello world 3" > test.txt
       

      # https://github.com/marketplace/actions/add-commit
      - uses: EndBug/add-and-commit@v9
        with:
          cwd: langchain-api-docs-html
          message: 'Update API docs build'